
TELEGRAM_KEY = "1234567890:AAFAKE_TEST_TOKEN_DO_NOT_USE_abcdefghijklmnopqrstuvwxyz"
MONGO_URI = "mongodb+srv://test_user:test_password@test-cluster.mongodb.net/test_db"
GEMINI_API_KEY = "AIzaSyFAKE_TEST_KEY_DO_NOT_USE_1234567890"
AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"